name: apparent
description: A Flutter app with language selection, dark/light mode, and bottom navigation.

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  easy_localization: ^3.0.3
  shared_preferences: ^2.2.2
  provider: ^6.1.1

flutter:
  uses-material-design: true
  assets:
    - assets/localization/en.json
    - assets/localization/es.json
